### ISSUE TITLE
Write tutorials/examples

### ISSUE THREAD

**Issue by domna** [FAIRmat-NFDI/pynxtools#489]
This includes several topics and may be split into further sub-issues

- [ ] FAIRmat-NFDI/nexus_definitions#105
- [ ] FAIRmat-NFDI/nexus_definitions#106
- [ ] FAIRmat-NFDI/nexus_definitions#107
- [ ] FAIRmat-NFDI/nexus_definitions#108
- [ ] FAIRmat-NFDI/nexus_definitions#109
- [ ] FAIRmat-NFDI/nexus_definitions#110

## Added during Sprint

- [ ] FAIRmat-NFDI/nexus_definitions#111

[Meeting ref](https://github.com/FAIRmat-NFDI/data-modeling/blob/main/mpes/meetings/2023-10-04_documentation.md#decisions)
